#docker run -it --rm -p 4200:4200 -v ${PWD}/src:/src frontend
FROM node:8.16.0
RUN mkdir -p /app
WORKDIR /app
RUN npm install -g @angular/cli
COPY . /app
#COPY package.json /app/
#RUN ["npm","install"]
#EXPOSE 4200
CMD ng serve --host 0.0.0.0 --port 4200
