#docker run -it --rm -p 4200:4200 -v ${pwd}/src:/src frontend
FROM node:10-alpine
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/
RUN ["npm","install"]
COPY . /app
EXPOSE 4200
CMD ["npm","start","--","--host","0.0.0.0","--poll","500"]
