version: "2"
services:
  web:
    image: userpanelui
    container_name: ui
    ports:
    - "4200:4200"
    command: npm start
  backend:
    image: userpanelserver
    container_name: server
    ports: 
    - "8081:8081"
    links:
      - mongo
  mongo:
    image: mongo